---
edit_url: "https://github.com/dhis2/dhis2-docs-implementation/blob/master/content/implementation/conceptual-design-principles.md"
revision_date: '2021-09-15'
tags:
- Implémentation
---

# Principes de conception { #conceptual-design-principles } 

Ce chapitre présente quelques principes clés de la conception du logiciel DHIS2. Connaître et comprendre ces principes permettra à l'utilisateur de mieux utiliser le logiciel lors de la personnalisation d'une base de données locale. Alors que ce chapitre présente les principes, les chapitres suivants expliquent en détail comment ils se traduisent dans le processus de conception de la base de données.

Les principes de conception suivants seront présentés dans ce chapitre :

  - Toutes les méta-données peuvent être ajoutées et modifiées via l'interface utilisateur

  - Un modèle de données flexible prend en charge l'intégration de différentes sources de données
    dans un référentiel de données unique

  - Entrée de données \!= Sortie des données

  - Analyse de données et rapports basés sur les indicateurs

  - Maintenir les données des établissements agrégées dans la base de données

  - Soutenir l'analyse des données à tous les niveaux du système de santé

Dans les sections qui suivent, chaque principe est décrit plus en détail.

## Toutes les méta-données peuvent être ajoutées et modifiées via l'interface utilisateur { #all-meta-data-can-be-added-and-modified-through-the-user-interface } 

L'application DHIS2 contient un ensemble d'outils génériques utilisés pour la collecte, la validation, la déclaration et l'analyse des données, mais le contenu de la base de données, c'est-à-dire les données à collecter, leur provenance et leur format, dépendra du contexte d'utilisation. Ces métadonnées doivent être ajoutées à l'application avant son utilisation. L'opération peut être effectuée via l'interface utilisateur et ne nécessite aucune programmation. Ceci permet aux experts du domaine d'être plus directement impliqués et de comprendre les détails du système d'information sanitaire que le logiciel prendra en charge.

Le logiciel sépare les métadonnées clés qui décrivent les données brutes stockées dans la base de données, c'est-à-dire les métadonnées stratégiques qui ne doivent pas beaucoup changer au fil du temps (pour éviter la corruption des données), et les métadonnées de haut niveau telles que les formules d'indicateurs, les règles de validation et les groupes utilisés pour l'agrégation, ainsi que les différentes présentations des formulaires de collecte et des rapports, qui ne sont pas si stratégiques et peuvent être modifiées au fil du temps sans que les données brutes n'en soient affectées. Étant donné que ces métadonnées de haut niveau peuvent être ajoutées et modifiées au fil du temps sans affecter les données brutes, un processus de personnalisation en continu est pris en charge. De nouvelles fonctionnalités sont généralement ajoutées au fil du temps, au fur et à mesure que l'équipe locale chargée de l'implémentation apprend de nouvelles fonctionnalités et que les utilisateurs réclament des analyses de données et des rapports plus avancés.

## Un modèle de données flexible permet à différentes sources de données d’être intégrées dans un référentiel de données unique { #a-flexible-data-model-supports-different-data-sources-to-be-integrated-in-one-single-data-repository } 

La conception du DHIS2 repose sur une approche intégrée du SIS et prend en compte l'intégration de différentes sources de données dans une base de données unique, souvent appelée référentiel de données intégré ou entrepôt de données.

Etant donné que le logiciel DHIS2 est un outil doté uniquement d'une ossature, sans formulaires ni rapports prédéfinis, il peut prendre en charge un grand nombre de sources de données agrégées différentes. Rien ne limite réellement son utilisation dans le secteur de la santé, bien que son utilisation dans d'autres secteurs soit encore très limitée. Tant que les données sont collectées par une unité d'organisation, c'est-à-dire un élément de données (avec éventuellement certaines catégories de désagrégation), et peuvent être représentées par une fréquence de période prédéfinie, elles peuvent être collectées et traitées dans DHIS2. Cette flexibilité fait du DHIS2 un outil puissant pour la mise en place de systèmes intégrés qui regroupent les outils de collecte, les indicateurs et les rapports de plusieurs programmes, services ou initiatives de santé. Une fois que les données sont définies, puis collectées ou importées dans une base de données DHIS2, il est possible de les analyser ensemble avec les autres données de la même base, quelle que soit la manière dont elles ont été collectées et le responsable de cette collecte. En plus de favoriser l'analyse intégrée des données et l'établissement de rapports, cette approche intégrée permet également de rationaliser la collecte des données et de réduire les doublons.

## Entrée de données \!= Sortie des données { #data-input-data-output } 

Le logiciel DHIS2 présente en trois dimensions, les données agrégées collectées et stockées dans la base de données : le "où" - unité d'organisation, le "quoi" - élément de données, et le "quand" - la période. L'unité d'organisation, l'élément de données et la période sont les trois dimensions de base qui permettent de décrire toute valeur de données dans DHIS2, que ce soit dans un formulaire de collecte de données, un graphique, une carte ou un rapport de synthèse agrégé. Lorsque les données sont collectées dans un formulaire électronique, parfois par le biais d'une image miroir des formulaires papier utilisés sur les lieux de collecte, chaque champ du formulaire peut être décrit en fonction de ces trois dimensions. Le formulaire lui-même n'est qu'un outil qui organise le processus de collecte des données. Il ne décrit pas les valeurs individuelles des données collectées et stockées dans la base de données. Le fait de pouvoir décrire une à une chaque valeur de données en définissant un élément de données (par exemple, doses de vaccin contre la rougeole administrées \<1 an) rend flexible le traitement, la validation et l'analyse des données, et permet de comparer les données entre les formulaires de collecte et les programmes de santé.

Par cette approche de la conception ou du modèle de données, DHIS2 se distingue des nombreuses applications logicielles SIS traditionnelles qui utilisent les formulaires de collecte de données comme principaux outils d'analyse. La figure ci-dessous montre l'importance particulière d'une conception plus fine du DHIS2, qui s'articule autour du concept d'éléments de données. Elle montre également la séparation entre l'entrée (la collecte des données) et la sortie (l'analyse des données), qui permet une analyse et une diffusion des données plus flexibles et variées. L'élément de données "Doses de vaccin contre la rougeole administrées \<1 an" est collecté dans un formulaire de collecte de données sur la vaccination des enfants. Il peut toutefois être utilisé à titre individuel en tant qu'indicateur (une formule) appelé "Couverture vaccinale contre la rougeole \<1 an" où il est combiné avec l'élément de données "Population \<1 an" collecté via un autre formulaire de collecte. Cette valeur calculée de l'indicateur peut ensuite être utilisée pour l'analyse des données à travers l'établissement de rapports, tels que des rapports personnalisés avec des graphiques, des tableaux croisés dynamiques ou sur une carte dans le module SIG.

![](resources/images/data_input_output.png)

## Analyse de données et rapports basés sur les indicateurs { #indicator-driven-data-analysis-and-reporting } 

L'élément de données tel que mentionné ci-dessus, c'est-à-dire la dimension clé qui décrit ce qui est collecté, est parfois qualifié d'indicateur dans d'autres contextes. Dans le DHIS2, il faut distinguer les éléments de données, qui décrivent les données brutes, par exemple les chiffres collectés, des indicateurs, qui sont basés sur des formules et décrivent des valeurs calculées, par exemple les taux de couverture ou d'incidence utilisés pour l'analyse des données. Les valeurs des indicateurs ne sont pas collectées de la même manière que les valeurs des (éléments) de données, mais sont calculées par l'application sur la base de formules définies par les utilisateurs. Ces formules sont composées d'un facteur (par exemple 1, 100, 100, 100 000), d'un numérateur et d'un dénominateur, les deux derniers étant des expressions basées sur un ou plusieurs éléments de données. Par exemple, l'indicateur "Couverture vaccinale contre la rougeole \<1 an" est défini par une formule avec un facteur 100, un numérateur ("doses de vaccin contre la rougeole administrées aux enfants de moins d'un an") et un dénominateur ("population cible âgée de moins d'un an"). L'indicateur "Taux d'abandon du Penta 1 au Penta 3" est une formule de 100 % x ("doses de Penta 1 administrées" - "doses de Penta 3 administrées") / ("doses de Penta 1 administrées"). Ces formules peuvent être ajoutées et modifiées via l'interface utilisateur par un utilisateur même peu formé, car elles sont faciles à configurer et n'interfèrent pas avec les valeurs de données stockées dans la base de données (l'ajout ou la modification d'un indicateur n'est donc pas une opération critique).

Les indicateurs représentent peut-être la fonction d'analyse de données la plus puissante du DHIS2, et tous les outils de rapport prennent en charge l'utilisation des indicateurs, comme le montre le rapport personnalisé dans la figure ci-dessus. La possibilité d'utiliser des données démographiques comme dénominateur permet de comparer les performances en matière de santé dans des zones géographiques avec des populations cibles différentes, ce qui est plus utile que de se contenter des chiffres bruts. Le tableau ci-dessous utilise à la fois les valeurs des données brutes (Doses) et les valeurs des indicateurs (Cov) pour les différents vaccins. Si l'on compare par exemple les deux premières unités d'organisation de la liste, le comté de Taita Taveta et le comté de Kilifi, pour la vaccination au Penta-1, on constate que si les chiffres bruts (659 contre 2088) indiquent que beaucoup plus de doses sont administrées à Kilifi, les taux de couverture (92,2 % contre 47,5 %) montrent que Taita Taveta vaccine mieux sa population cible âgée de moins d'un an. Si l'on examine la dernière colonne (Immuniz. Compl. % ou % de complétude de la vaccination) qui indique la complétude du rapport du formulaire de vaccination pour la même période, on constate que les chiffres sont plus ou moins les mêmes dans les deux comtés comparés, ce qui nous indique que les taux de couverture entre ces deux comtés peuvent être comparés de façon raisonnable.

![](resources/images/indicator_report.png)

## Maintenir les données désagrégées des établissements dans la base de données { #maintain-disaggregated-facility-data-in-the-database } 

Lorsque les données sont collectées et stockées dans le DHIS2, elles restent désagrégées dans la base de données avec le même niveau de détail que lors de leur collecte. Un système de base de données pour le SIS offre un avantage majeur par rapport à un système basé sur du papier ou une feuille de calcul. Le système est conçu pour stocker de grandes quantités de données et permet toujours d'accéder au niveau le plus détaillé possible, qui n'est limité que par la manière dont les données ont été collectées ou importées dans la base de données DHIS2. Dans la perspective d'un SIS national, il est recommandé de garder les données désagrégées au niveau de l'établissement de santé, qui est souvent le niveau le plus bas dans la hiérarchie de l'unité d'organisation. Cela peut se faire par le biais d'un système hybride (papier et ordinateur). Les données peuvent être transmises par les établissements de santé aux bureaux de district sur papier (par exemple sur des formulaires de synthèse mensuels pour un établissement spécifique), puis le bureau de district saisit toutes les données de l'établissement dans DHIS2 au moyen des formulaires électroniques de collecte de données, établissement par établissement. Cela permettra aux équipes de gestion sanitaire des districts d'analyser les données par établissement et de fournir, par exemple, des copies imprimées des rapports de retour d'information générés par DHIS2, y compris des comparaisons entre établissements, aux responsables des établissements dans leur district.

## Soutenir l'analyse des données à tous les niveaux du système de santé { #support-data-analysis-at-any-level-in-the-health-system } 

Bien que le nom DHIS2 indique une focalisation sur le district, l'application fournit les mêmes outils et fonctionnalités à tous les niveaux du système de santé. Dans tous les outils de rapports, les utilisateurs peuvent sélectionner l'unité d'organisation ou le niveau d'unité d'organisation à analyser et les données affichées seront automatiquement agrégées jusqu'au niveau sélectionné. DHIS2 utilise la hiérarchie des unités d'organisation pour agréger les données vers les niveaux supérieurs et fournit des données pour toutes les unités d'organisation de cette hiérarchie. La plupart des rapports sont effectués de manière à inviter les utilisateurs à sélectionner une unité d'organisation, ce qui permet de réutiliser les mêmes présentations de rapport, quel que soit le niveau. Vous pouvez également, si vous le souhaitez, adapter les présentations des rapports à un niveau spécifique du système de santé si les besoins entre niveaux diffèrent.

Dans le module SIG, les utilisateurs peuvent analyser les données au niveau infranational, par exemple, puis, en cliquant sur la carte (sur une région ou une province, par exemple), descendre au niveau suivant et continuer ainsi jusqu'à la source des données au niveau de l'établissement. Les tableaux croisés dynamiques d'Excel associés à la base de données DHIS2 offrent une fonctionnalité d'exploration similaire.

Pour accélérer les performances et réduire le temps de réponse lors de la fourniture de données agrégées, qui peuvent inclure plusieurs calculs (par exemple, l'addition des données de 8 000 établissements), DHIS2 calcule au préalable toutes les valeurs agrégées possibles et les stocke dans ce que l'on appelle un datamart (entrepôt de données). Ce datamart peut être programmé pour être exécuté (reconstitué) à un intervalle de temps donné, par exemple tous les soirs.

